settings:
  parallel: true

driver:
  name: docker

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
  - name: default
    run_list:
      - recipe[yum_test::default]
