name 'yum_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test_yum'
long_description 'Installs/Configures test_yum'
version '0.1.0'

depends 'yum'
depends 'yum-centos'
depends 'yum-epel'
